storewebcore.Web/Areas/Settings/Controllers/CultureController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace storewebcore.Web.Areas.Settings.Controllers
{
    [Area("Settings")]
    public class CultureController : Controller
    {
        [AllowAnonymous]
        [HttpPost]
        public IActionResult SetCulture(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

storewebcore.Web/Controllers/CultureController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace storewebcore.Web.Controllers
{
    public class CultureController : Controller
    {
        [AllowAnonymous]
        [HttpPost]
        public IActionResult SetCulture(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

storewebcore.Web/Views/Shared/Components/Culture/CultureViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.Culture
{
    public class CultureViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/Footer/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.Footer
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/FormModal/FormModalViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.FormModal
{
    public class FormModalViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/Header/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.Header
{
    public class HeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/ImageModal/ImageModalViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.ImageModal
{
    public class ImageModalViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/Logout/LogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.Logout
{
    public class LogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/Sidebar/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.Sidebar
{
    public class SidebarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/Title/TitleViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace storewebcore.Web.Views.Shared.Components.Title
{
    public class TitleViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

storewebcore.Web/Views/Shared/Components/Culture/Default.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = Localizer.GetString(c.NativeName) })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">

    <a class="nav-link" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">
            @if (requestCulture != null)
            {
                @if (requestCulture.RequestCulture.UICulture.Name == "en")
                {
                    <i class="flag-icon flag-icon-gb"></i>
                }
                else if (requestCulture.RequestCulture.UICulture.Name == "ar")
                {
                    <i class="flag-icon flag-icon-sa"></i>
                }
                else if (requestCulture.RequestCulture.UICulture.Name == "fr")
                {
                    <i class="flag-icon flag-icon-fr"></i>
                }
                @requestCulture.RequestCulture.UICulture.NativeName
            }
        </span>
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        @foreach (var culture in cultureItems)
        {

            <form style="padding:0px!important"
                  asp-area="Settings"
                  asp-controller="Culture"
                  asp-action="SetCulture"
                  asp-route-returnUrl="@returnUrl"
                  asp-route-culture="@culture.Value"
                  method="post"
                  class="form-horizontal"
                  role="form">
                <button type="submit" class="dropdown-item">
                    @if (culture.Value == "en" || culture.Value == "en-US")
                    {
                        <i class="flag-icon flag-icon-gb"></i>
                    }
                    else if (culture.Value == "ar")
                    {
                        <i class="flag-icon flag-icon-sa"></i>
                    }
                    else if (culture.Value == "fr")
                    {
                        <i class="flag-icon flag-icon-fr"></i>
                    }

                    @culture.Text
                </button>
            </form>
        }
    </div>
</div>