storewebcore.Web/Areas/Admin/Models/UserViewModel.cs
namespace storewebcore.Web.Areas.Admin.Models
{
    public class UserViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public bool IsActive { get; set; } = true;
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }

        public byte[] ProfilePicture { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Id { get; set; }
    }
}

storewebcore.Web/Areas/Admin/Controllers/UserController.cs
using storewebcore.Application.Constants;
using storewebcore.Application.Enums;
using storewebcore.Infrastructure.Identity.Models;
using storewebcore.Web.Abstractions;
using storewebcore.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;

namespace storewebcore.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : BaseController<UserController>
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [Authorize(Policy = Permissions.Users.View)]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadAll()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            var model = _mapper.Map<IEnumerable<UserViewModel>>(allUsersExceptCurrentUser);
            return PartialView("_ViewAll", model);
        }

        public async Task<IActionResult> OnGetCreate()
        {
            return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_Create", new UserViewModel()) });
        }

        [HttpPost]
        public async Task<IActionResult> OnPostCreate(UserViewModel userModel)
        {
            if (ModelState.IsValid)
            {
                MailAddress address = new MailAddress(userModel.Email);
                string userName = address.User;
                var user = new ApplicationUser
                {
                    UserName = userName,
                    Email = userModel.Email,
                    FirstName = userModel.FirstName,
                    LastName = userModel.LastName,
                    EmailConfirmed = true,
                };
                var result = await _userManager.CreateAsync(user, userModel.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, Roles.Basic.ToString());
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                    var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
                    var users = _mapper.Map<IEnumerable<UserViewModel>>(allUsersExceptCurrentUser);
                    var htmlData = await _viewRenderer.RenderViewToStringAsync("_ViewAll", users);
                    _notify.Success($"Account for {user.Email} created.");
                    return new JsonResult(new { isValid = true, html = htmlData });
                }
                foreach (var error in result.Errors)
                {
                    _notify.Error(error.Description);
                }
                var html = await _viewRenderer.RenderViewToStringAsync("_Create", userModel);
                return new JsonResult(new { isValid = false, html = html });
            }
            return default;
        }
    }
}

storewebcore.Web/Areas/Admin/Controllers/UserRoleController.cs
using storewebcore.Infrastructure.Identity.Models;
using storewebcore.Web.Abstractions;
using storewebcore.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace storewebcore.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserRoleController : BaseController<UserRoleController>
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserRoleController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(string userId)
        {
            var viewModel = new List<UserRolesViewModel>();
            var user = await _userManager.FindByIdAsync(userId);
            ViewData["Title"] = $"{user.UserName} - Roles";
            ViewData["Caption"] = $"Manage {user.Email}'s Roles.";
            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                viewModel.Add(userRolesViewModel);
            }
            var model = new ManageUserRolesViewModel()
            {
                UserId = userId,
                UserRoles = viewModel
            };

            return View(model);
        }

        public async Task<IActionResult> Update(string id, ManageUserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            result = await _userManager.AddToRolesAsync(user, model.UserRoles.Where(x => x.Selected).Select(y => y.RoleName));
            var currentUser = await _userManager.GetUserAsync(User);
            await _signInManager.RefreshSignInAsync(currentUser);
            await Infrastructure.Identity.Seeds.DefaultSuperAdminUser.SeedAsync(_userManager, _roleManager);
            _notify.Success($"Updated Roles for User '{user.Email}'");
            return RedirectToAction("Index", new { userId = id });
        }
    }
}

storewebcore.Web/Areas/Admin/Views/User/Index.cshtml
@{
    ViewData["Title"] = localizer["Users"];
    ViewData["Caption"] = localizer["Manage Users here"];
}
<div class="card">
    <div class="col-sm-12" style="padding:20px">
        <a onclick="jQueryModalGet('/admin/user/OnGetCreate','Create User')" class="btn bg-success">
            <i class="fa fa-plus-square"></i> Create
        </a>
        <a id="reload" class="btn btn-primary text-white">
            <i class="fa fas fa-bolt"></i>
            Reload
        </a>
    </div>
    <div id="viewAll" class="card-body table-responsive">
    </div>
</div>
@section Scripts
{
    <script src="~/js/site.js"></script>
    <script>
        $(document).ready(function () {
            $("#userTable").DataTable();
            loadData();
            $('#reload').on('click', function () {
                loadData();
            });
        });
        function loadData() {
            $('#viewAll').load('/admin/user/LoadAll');
        }
    </script>
}

storewebcore.Web/Areas/Admin/Views/User/_Create.cshtml
@using storewebcore.Web.Areas.Admin.Models
@model UserViewModel
<form id="create-form" method="post" asp-area="Admin" asp-controller="User" asp-action="OnPostCreate" onsubmit="return jQueryModalPost(this);">
    <div class="form-group row">
        <label class="col-md-3 col-form-label">@localizer["FirstName"]</label>
        <div class="col-md-9">
            <input type="text" asp-for="FirstName" name="FirstName" class="form-control">
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label">@localizer["LastName"]</label>
        <div class="col-md-9">
            <input type="text" asp-for="LastName" name="LastName" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label">@localizer["Email"]</label>
        <div class="col-md-9">
            <input type="email" asp-for="Email" name="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label">@localizer["Password"]</label>
        <div class="col-md-9">
            <input type="password" asp-for="Password" name="Password" class="form-control">
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label">@localizer["ConfirmPassword"]</label>
        <div class="col-md-9">
            <input type="password" asp-for="ConfirmPassword" name="ConfirmPassword" class="form-control">
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group justify-content-between" style="margin-bottom: 0px !important">
        <button type="submit" class="btn btn-success">Save</button>
        <button type="submit" class="btn btn-default close-button" data-dismiss="modal">Cancel</button>
    </div>
</form>
<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

storewebcore.Web/Areas/Admin/Views/User/_ViewAll.cshtml
@using storewebcore.Web.Areas.Admin.Models
@model IEnumerable<UserViewModel>
<table class="table table-striped" id="userTable">
    <thead>
        <tr>
            <th>
                @localizer["User"]
            </th>
            <th>
                @localizer["Email"]
            </th>
            <th>
                @localizer["Status"]
            </th>
            <th style="width:10%">
                @localizer["Actions"]
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    <div class="row">
                        @if (@user.ProfilePicture != null && user.ProfilePicture.Length > 0)
                        {
                            <div class="col-sm" style=" max-width: 80px;margin-right: 20px;">
                                <img class="img-profile rounded-circle" style="height: 75px;width:75px;object-fit: cover;" src="data:image/*;base64,@(Convert.ToBase64String(@user.ProfilePicture))">
                            </div>
                        }
                        else

                        {
                            <div class="col-sm" style="max-width:80px; margin-right: 20px;">
                                <img class="img-profile rounded-circle" style="height: 75px;width:75px;object-fit: cover;" src="~/images/default-user.png">
                            </div>
                        }
                        <div class="col-sm">
                            <a>
                                @user.FirstName @user.LastName
                            </a>
                            <br>
                            <small>
                                @user.Id
                            </small>
                        </div>
                    </div>
                </td>
                <td>
                    <a>
                        @user.Email
                    </a>
                    <br>
                    <small>
                        @if (user.EmailConfirmed)
                        {
                            <span class="badge badge-success">@localizer["Email Confirmed"]</span>
                        }
                        else
                        {
                            <span class="badge badge-danger">@localizer["Email Not Confirmed"]</span>
                        }
                    </small>
                </td>
                <td>
                    @if (user.IsActive)
                    {
                        <span class="badge badge-success">@localizer["Active"]</span>
                    }
                    else
                    {
                        <span class="badge badge-danger">@localizer["Deactivated"]</span>
                    }
                </td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action
                        </button>
                        <div class="dropdown-menu shadow animated--grow-in">
                            <a style='margin-right:16px' asp-area="Identity" asp-page="/Profile" asp-route-userId="@user.Id" class="dropdown-item">
                                <i class="fas fa-user"></i> @localizer["Profile"]
                            </a>
                            <a style='margin-right:16px' asp-controller="UserRole" asp-action="Index" asp-route-userId="@user.Id" class="dropdown-item">
                                <i class="fas fa-wrench"></i> @localizer["Manage Roles"]
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $("#userTable").DataTable();
    });
</script>